# ----------------------------
# Neon Slice - TI-84 Plus CE
# ----------------------------

NAME = SLICE
ICON = icon.png
DESCRIPTION = "Neon Slice"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
